// src/api/exams.js
import api from './axios'

export const getExams         = (params)  => api.get('/exams', { params })
export const createExam       = (data)    => api.post('/exams', data)
export const createBulkExams   = (data)    => api.post('/exams/bulk', data)
export const updateExamStatus = (id,data) => api.patch(`/exams/${id}`, data)
export const updateExamTimetable = (id,data) => api.patch(`/exams/${id}/timetable`, data)
export const getExamSubjects  = (id)      => api.get(`/exams/${id}/subjects`)
export const approveAllExamSubjects = (id) => api.patch(`/exams/${id}/subjects/approve-all`)
export const reviewExamSubject = (examId, subjectId, data) => api.patch(`/exams/${examId}/subjects/${subjectId}/review`, data)
export const deleteExam       = (id)      => api.delete(`/exams/${id}`)
export const downloadExamTimetablePdf = (id) => api.get(`/exams/${id}/timetable/pdf`, { responseType: 'blob' })
export const downloadClassTimetablePdf = (params) => api.get('/exams/class/timetable/pdf', { params, responseType: 'blob' })
export const downloadAllClassesTimetablePdf = (params) => api.get('/exams/timetable/all-classes/pdf', { params, responseType: 'blob' })
export const getSubjects      = (classId) => api.get(`/classes/${classId}/subjects`)
export const enterMarks       = (data)    => api.post('/results/enter', data)
export const getResults       = (enrollmentId) => api.get(`/results/${enrollmentId}`)
export const getReportCard     = (enrollmentId) => api.get(`/results/${enrollmentId}/report-card`, { responseType: 'blob' })
export const getReportCardData = (enrollmentId, params) => api.get(`/results/${enrollmentId}/report-card/data`, { params })
export const getMarksTemplate  = (id, subjectId) => api.get(`/exams/${id}/subjects/${subjectId}/template`, { responseType: 'blob' })
export const uploadMarksExcel  = (id, subjectId, data) => api.post(`/exams/${id}/subjects/${subjectId}/upload-marks`, data)
export const getClassResults  = (params)  => api.get('/results/class', { params })
export const downloadClassResultSheetPdf = (params) => api.get('/results/class/download', { params, responseType: 'blob' })
export const calculateResults = (data)    => api.post('/results/calculate', data)
export const bulkCalculateResults = (data) => api.post('/results/bulk-calculate', data)
export const overrideResult   = (data)    => api.patch('/results/override', data)
export const releaseResult    = (data)    => api.patch('/results/release', data)
export const overrideExamMark = (data)    => api.patch('/results/marks/override', data)
export const deleteResult     = (enrollmentId, sessionId) => api.delete(`/results/${enrollmentId}`, { params: { session_id: sessionId } })
export const getExamMarks     = (params) => api.get('/results/exam-marks', { params })
