// src/api/index.js — barrel export for all API modules
export * as studentsApi   from './studentsApi'
export * as sessionsApi   from './sessionsApi'
export * as attendanceApi from './attendanceApi'
export * as feesApi       from './feesApi'
export * as examsApi      from './examsApi'
export * as auditApi      from './auditApi'
import { getCertificates, generateCertificate, revokeCertificate, getSettings, updateSettings } from './certificateApi'
import * as certificateApiNamespace from './certificateApi'
export const certificateApi = { ...certificateApiNamespace, getCertificates, generateCertificate, revokeCertificate, getSettings, updateSettings }
export * as classApi      from './classApi'
export * as streamApi     from './streamApi'
export * as subjectApi    from './subjectApi'
export * as teacherApi    from './teacherApi'
export * as accountantApi        from './accountantApi'
export * as adminTeacherControlApi from './adminTeacherControlApi'
export * as expenseApi           from './expenseApi'
export * as familyApi            from './familyApi'
export * as feedbackApi          from './feedbackApi'
export * as healthApi            from './healthApi'
export * as inventoryApi         from './inventoryApi'
export * as libraryApi           from './libraryApi'
export * as parentApi            from './parentApi'
export * as payrollApi           from './payrollApi'
export * as staffAttendanceApi   from './staffAttendanceApi'
export * as studentApi           from './studentApi'
export * as studentLeavingApi    from './studentLeavingApi'
import { getAlumniStats, getAlumniDirectory, getAlumniProfile, upsertAlumniProfile, downloadAlumniPdf, listAlumniEvents, createAlumniEvent, updateAlumniEvent, deleteAlumniEvent } from './alumniApi'
import * as alumniApiNamespace from './alumniApi'
export const alumniApi = { ...alumniApiNamespace, getAlumniStats, getAlumniDirectory, getAlumniProfile, upsertAlumniProfile, downloadAlumniPdf, listAlumniEvents, createAlumniEvent, updateAlumniEvent, deleteAlumniEvent }
export * as transportApi         from './transportApi'
export * as userManagementApi    from './userManagementApi'
import { adminListNotices, adminCreateNotice, adminUpdateNotice, adminDeleteNotice, teacherListNotices, teacherCreateNotice, teacherUpdateNotice, teacherDeleteNotice, getAccountantPortalNotices, getStudentNotices, markNoticeRead, pinNotice, unpinNotice } from './noticesApi'
import * as noticesApiNamespace from './noticesApi'
export const noticesApi = { ...noticesApiNamespace, adminListNotices, adminCreateNotice, adminUpdateNotice, adminDeleteNotice, teacherListNotices, teacherCreateNotice, teacherUpdateNotice, teacherDeleteNotice, getAccountantPortalNotices, getStudentNotices, markNoticeRead, pinNotice, unpinNotice }
export * as academicCalendarApi  from './academicCalendarApi'
import { updateSettings as settingsApi_updateSettings } from './settingsApi'
import * as settingsApiNamespace from './settingsApi'
export const settingsApi = { ...settingsApiNamespace, updateSettings: settingsApi_updateSettings }
export * from './analyticsApi'
import { getComplianceReport } from './complianceApi'
import * as complianceApiNamespace from './complianceApi'
export const complianceApi = { ...complianceApiNamespace, getComplianceReport }
import { getDashboardSummary } from './aiAnalysisApi'
import * as aiAnalysisApiNamespace from './aiAnalysisApi'
export const aiAnalysisApi = { ...aiAnalysisApiNamespace, getDashboardSummary }
import { getDashboardInsights, getRiskStudents } from './aiInsightsApi'
import * as aiInsightsApiNamespace from './aiInsightsApi'
export const aiInsightsApi = { ...aiInsightsApiNamespace, getDashboardInsights, getRiskStudents }
