// src/api/index.js — barrel export for all API modules
export * as authApi       from './auth'
export * as studentsApi   from './students'
export * as sessionsApi   from './sessions'
export * as enrollmentsApi from './enrollments'
export * as attendanceApi from './attendance'
export * as feesApi       from './fees'
export * as examsApi      from './exams'
export * as auditApi      from './audit'
export * as classApi      from './classApi'
export * as subjectApi    from './subjectApi'
export * as teacherApi    from './teacherApi'
