// src/api/index.js — barrel export for all API modules
export * as authApi       from './auth'
export * as studentsApi   from './studentsApi'
export * as sessionsApi   from './sessionsApi'
export * as enrollmentsApi from './enrollmentsApi'
export * as attendanceApi from './attendanceApi'
export * as feesApi       from './feesApi'
export * as examsApi      from './examsApi'
export * as auditApi      from './auditApi'
export * as classApi      from './classApi'
export * as subjectApi    from './subjectApi'
export * as teacherApi    from './teacherApi'
