import api from './axios'

export const getStudentDashboard = () => api.get('/student/dashboard')
export const getStudentTodaySchedule = () => api.get('/student/dashboard/today-schedule')
export const getStudentUpcomingEvents = () => api.get('/student/dashboard/upcoming-events')
export const getStudentAchievements = () => api.get('/student/dashboard/achievements')
export const getStudentAttendance = (params = {}) => api.get('/student/attendance', { params })
export const getStudentAttendanceSummary = () => api.get('/student/attendance/summary')
export const getStudentAttendanceTrend = () => api.get('/student/attendance/trend')
export const getStudentAttendanceExport = () => api.get('/student/attendance/export')
export const getStudentResults = () => api.get('/student/results')
export const getStudentResultByExam = (examId) => api.get(`/student/results/${examId}`)
export const getStudentReportCard = (examId) => api.get(`/student/results/report-card/${examId}`)
export const getStudentResultExport = (examId) => api.get(`/student/results/export/${examId}`)
export const getStudentFees = () => api.get('/student/fees')
export const getStudentFeeSummary = () => api.get('/student/fees/summary')
export const getStudentFeeInvoiceDetail = (invoiceId) => api.get(`/student/fees/${invoiceId}`)
export const getStudentFeePayments = () => api.get('/student/fees/payments')
export const getStudentFeeReceipt = (paymentId) => api.get(`/student/fees/receipts/${paymentId}`)
export const getStudentTimetable = () => api.get('/student/timetable')
export const getStudentTimetableToday = () => api.get('/student/timetable/today')
export const getStudentCurrentPeriod = () => api.get('/student/timetable/current-period')
export const getStudentExamSchedule = () => api.get('/student/timetable/exam-schedule')
export const getStudentHomework = (params = {}) => api.get('/student/homework', { params })
export const getStudentHomeworkDetail = (homeworkId) => api.get(`/student/homework/${homeworkId}`)
export const submitStudentHomework = (homeworkId, data) => api.post(`/student/homework/${homeworkId}/submit`, data)
export const getStudentHomeworkSubmissions = () => api.get('/student/homework/submissions')
export const getStudentChatContacts = () => api.get('/student/chat/contacts')
export const getStudentChatConversations = () => api.get('/student/chat/conversations')
export const createStudentChatConversation = (data) => api.post('/student/chat/conversations', data)
export const getStudentChatMessages = (id) => api.get(`/student/chat/conversations/${id}/messages`)
export const sendStudentChatMessage = (id, data) => api.post(`/student/chat/conversations/${id}/messages`, data)
export const getStudentNotices = (params = {}) => api.get('/student/notices', { params })
export const markStudentNoticeRead = (noticeId) => api.post(`/student/notices/${noticeId}/read`)
export const pinStudentNotice = (noticeId) => api.post(`/student/notices/${noticeId}/pin`)
export const unpinStudentNotice = (noticeId) => api.delete(`/student/notices/${noticeId}/pin`)
export const getStudentProfile = () => api.get('/student/profile')
export const createStudentCorrectionRequest = (data) => api.post('/student/profile/correction-request', data)
export const getStudentCorrectionRequests = () => api.get('/student/profile/correction-requests')
export const changeStudentPassword = (data) => api.post('/student/profile/change-password', data)
export const getStudentAchievementsList = () => api.get('/student/achievements')
export const getStudentAcademicHistory = () => api.get('/student/history')
export const getStudentMaterials = (params = {}) => api.get('/student/materials', { params })
export const getStudentMaterialDetail = (materialId) => api.get(`/student/materials/${materialId}`)
