import api from './axios'

export const getTeacherDashboard = () => api.get('/teacher/dashboard')
export const getTeacherTodaySchedule = () => api.get('/teacher/dashboard/today-schedule')
export const getTeacherPendingTasks = () => api.get('/teacher/dashboard/pending-tasks')
export const getTeacherRecentActivity = () => api.get('/teacher/dashboard/recent-activity')
export const getTeacherMyClasses = () => api.get('/teacher/my-classes')
export const getTeacherMyClassOverview = (id) => api.get(`/teacher/my-classes/${id}/overview`)
export const getTeacherAttendanceStatus = () => api.get('/teacher/attendance/status')
export const getTeacherAttendanceStudents = (params) => api.get('/teacher/attendance/students', { params })
export const markTeacherAttendance = (data) => api.post('/teacher/attendance/mark', data)
export const bulkMarkTeacherAttendance = (data) => api.post('/teacher/attendance/bulk-mark', data)
export const getTeacherAttendanceRegister = (params) => api.get('/teacher/attendance/register', { params })
export const getTeacherAttendanceSummary = (params) => api.get('/teacher/attendance/reports/summary', { params })
export const getTeacherAttendanceBelowThreshold = (params) => api.get('/teacher/attendance/reports/below-threshold', { params })
export const getTeacherAttendanceChronicAbsentees = (params) => api.get('/teacher/attendance/reports/chronic-absentees', { params })
export const getTeacherMarksExams = () => api.get('/teacher/marks/exams')
export const getTeacherMarksEntry = (params) => api.get('/teacher/marks/entry', { params })
export const saveTeacherMark = (data) => api.post('/teacher/marks/save', data)
export const bulkSaveTeacherMarks = (data) => api.post('/teacher/marks/bulk-save', data)
export const submitTeacherMarks = (data) => api.post('/teacher/marks/submit', data)
export const getTeacherMarksSummary = (params) => api.get('/teacher/marks/summary', { params })
export const getTeacherStudents = (params) => api.get('/teacher/students', { params })
export const getTeacherStudentDetail = (id) => api.get(`/teacher/students/${id}`)
export const getTeacherStudentAttendance = (id) => api.get(`/teacher/students/${id}/attendance`)
export const getTeacherStudentResults = (id) => api.get(`/teacher/students/${id}/results`)
export const getTeacherStudentRemarks = (id) => api.get(`/teacher/students/${id}/remarks`)
export const getTeacherRemarks = () => api.get('/teacher/remarks')
export const createTeacherRemark = (data) => api.post('/teacher/remarks', data)
export const updateTeacherRemark = (id, data) => api.patch(`/teacher/remarks/${id}`, data)
export const getTeacherChatContacts = () => api.get('/teacher/chat/contacts')
export const getTeacherChatConversations = () => api.get('/teacher/chat/conversations')
export const createTeacherChatConversation = (data) => api.post('/teacher/chat/conversations', data)
export const getTeacherChatMessages = (id) => api.get(`/teacher/chat/conversations/${id}/messages`)
export const sendTeacherChatMessage = (id, data) => api.post(`/teacher/chat/conversations/${id}/messages`, data)
export const getTeacherTimetable = () => api.get('/teacher/timetable')
export const getTeacherTimetableToday = () => api.get('/teacher/timetable/today')
export const getTeacherCurrentPeriod = () => api.get('/teacher/timetable/current-period')
export const getTeacherExamTimetable = () => api.get('/teacher/exam-timetable')
export const getTeacherHomework = (params) => api.get('/teacher/homework', { params })
export const createTeacherHomework = (data) => api.post('/teacher/homework', data)
export const updateTeacherHomework = (id, data) => api.patch(`/teacher/homework/${id}`, data)
export const deleteTeacherHomework = (id) => api.delete(`/teacher/homework/${id}`)
export const getTeacherHomeworkSubmissions = (id) => api.get(`/teacher/homework/${id}/submissions`)
export const submitTeacherHomework = (id, data) => api.post(`/teacher/homework/${id}/submit`, data)
export const gradeTeacherHomework = (id, data) => api.post(`/teacher/homework/${id}/grade`, data)
export const remindTeacherHomework = (id) => api.post(`/teacher/homework/${id}/remind`)
export const getTeacherNotices = (params) => api.get('/notices/teacher', { params })
export const createTeacherNotice = (data) => api.post('/notices/teacher', data)
export const updateTeacherNotice = (id, data) => api.patch(`/notices/teacher/${id}`, data)
export const deleteTeacherNotice = (id) => api.delete(`/notices/teacher/${id}`)
export const markTeacherNoticeRead = (id, source = 'unified') => api.post(`/notices/teacher/${id}/read?source=${source}`)
export const getTeacherLeaveBalance = () => api.get('/teacher/leave/balance')
export const getTeacherLeaveApplications = () => api.get('/teacher/leave/applications')
export const applyTeacherLeave = (data) => api.post('/teacher/leave/apply', data)
export const cancelTeacherLeave = (id) => api.patch(`/teacher/leave/${id}/cancel`)
export const getTeacherProfile = () => api.get('/teacher/profile')
export const updateTeacherProfileContact = (data) => api.patch('/teacher/profile/contact', data)
export const changeTeacherPassword = (data) => api.post('/teacher/profile/change-password', data)
export const createTeacherCorrectionRequest = (data) => api.post('/teacher/profile/correction-request', data)
