import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// ── Shared helpers ─────────────────────────────────────────────────────

const PAGE_W = 210
const MARGIN = 14
const CONTENT_W = PAGE_W - MARGIN * 2

function formatDate(dateStr) {
  if (!dateStr) return '—'
  return new Date(dateStr).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
}

function formatQty(qty) {
  return parseFloat(qty || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })
}

function drawHeader(doc, school, title, subtitle) {
  // School name
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 30)
  doc.text(school?.name || 'School Name', MARGIN, 18)

  // School address
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(
    [school?.address, school?.phone, school?.email].filter(Boolean).join('  |  '),
    MARGIN, 24
  )

  // Divider
  doc.setDrawColor(200, 200, 200)
  doc.line(MARGIN, 27, PAGE_W - MARGIN, 27)

  // Report title
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 30)
  doc.text(title, PAGE_W / 2, 35, { align: 'center' })

  if (subtitle) {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(120, 120, 120)
    doc.text(subtitle, PAGE_W / 2, 41, { align: 'center' })
  }

  return 47  // returns Y position after header
}

function drawSummaryBox(doc, startY, summaryItems) {
  // summaryItems: [{ label, value }]
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setFillColor(248, 249, 252)
  doc.roundedRect(MARGIN, startY, CONTENT_W, 12, 2, 2, 'F')

  const colW = CONTENT_W / summaryItems.length
  summaryItems.forEach((item, i) => {
    const x = MARGIN + colW * i + colW / 2
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(50, 50, 50)
    doc.text(String(item.value), x, startY + 5, { align: 'center' })
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(130, 130, 130)
    doc.text(item.label, x, startY + 9.5, { align: 'center' })
  })

  return startY + 17
}

function drawFooter(doc, generatedBy, generatedAt) {
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(150, 150, 150)
    doc.line(MARGIN, 283, PAGE_W - MARGIN, 283)
    doc.text(
      `Generated by: ${generatedBy || 'Administrator'}  |  ${formatDate(generatedAt)}`,
      MARGIN, 287
    )
    doc.text(`Page ${i} of ${pageCount}`, PAGE_W - MARGIN, 287, { align: 'right' })
  }
}

// ── PDF 1 — Item Catalog ───────────────────────────────────────────────

export function generateItemCatalogPdf(data) {
  const { school, items = [], generated_by, generated_at } = data

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const totalItems    = items.length
  const lowStockCount = items.filter(i => parseFloat(i.reorder_level) > 0 && parseFloat(i.quantity) <= parseFloat(i.reorder_level)).length
  const categories    = [...new Set(items.map(i => i.category))].length

  const subtitle = `Generated: ${formatDate(generated_at)}  |  By: ${generated_by || 'Administrator'}`
  let y = drawHeader(doc, school, 'INVENTORY CATALOG REPORT', subtitle)

  y = drawSummaryBox(doc, y, [
    { label: 'Total Items',      value: totalItems },
    { label: 'Categories',       value: categories },
    { label: 'Low Stock Alerts', value: lowStockCount },
  ])

  // Group by category
  const grouped = items.reduce((acc, item) => {
    if (!acc[item.category]) acc[item.category] = []
    acc[item.category].push(item)
    return acc
  }, {})

  let isFirstGroup = true
  Object.entries(grouped).forEach(([category, catItems]) => {
    autoTable(doc, {
      startY: isFirstGroup ? y : undefined,
      head: [[
        { content: `Category: ${category}`, colSpan: 7,
          styles: { fillColor: [237, 242, 255], textColor: [50, 80, 200], fontStyle: 'bold', fontSize: 8 }
        }
      ]],
      body: [],
      margin: { left: MARGIN, right: MARGIN },
      styles: { cellPadding: 2 },
      theme: 'plain',
    })

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY,
      head: [['#', 'Item Name', 'Unit', 'Current Stock', 'Reorder Level', 'Location', 'Status']],
      body: catItems.map((item, idx) => {
        const isLow = parseFloat(item.reorder_level || 0) > 0 &&
                      parseFloat(item.quantity || 0) <= parseFloat(item.reorder_level || 0)
        let desc = item.description || ''
        if (desc.length > 80) desc = desc.substring(0, 77) + '...'
        return [
          idx + 1,
          item.name + (desc ? `\n${desc}` : ''),
          item.unit,
          formatQty(item.quantity),
          formatQty(item.reorder_level) || '—',
          item.location || '—',
          isLow ? '⚠ LOW' : '✓ OK'
        ]
      }),
      margin: { left: MARGIN, right: MARGIN },
      headStyles: { fillColor: [60, 80, 180], textColor: 255, fontStyle: 'bold', fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 8,  halign: 'center' },
        1: { cellWidth: 55 },
        2: { cellWidth: 18, halign: 'center' },
        3: { cellWidth: 24, halign: 'right' },
        4: { cellWidth: 24, halign: 'right' },
        5: { cellWidth: 30 },
        6: { cellWidth: 18, halign: 'center' },
      },
      didParseCell(data) {
        if (data.column.index === 6 && data.cell.raw === '⚠ LOW') {
          data.cell.styles.textColor = [200, 40, 40]
          data.cell.styles.fontStyle = 'bold'
        }
        if (data.column.index === 6 && data.cell.raw === '✓ OK') {
          data.cell.styles.textColor = [30, 140, 70]
        }
      },
      alternateRowStyles: { fillColor: [250, 251, 255] },
    })

    isFirstGroup = false
  })

  // Low stock alert section at end
  const lowItems = items.filter(i =>
    parseFloat(i.reorder_level) > 0 && parseFloat(i.quantity) <= parseFloat(i.reorder_level)
  )
  if (lowItems.length > 0) {
    const alertY = doc.lastAutoTable.finalY + 8
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(200, 40, 40)
    doc.text('⚠  Items Requiring Immediate Restocking', MARGIN, alertY)

    autoTable(doc, {
      startY: alertY + 3,
      head: [['Item Name', 'Category', 'Unit', 'Current Stock', 'Reorder Level', 'Shortfall']],
      body: lowItems.map(i => [
        i.name, i.category, i.unit,
        formatQty(i.quantity),
        formatQty(i.reorder_level),
        formatQty(parseFloat(i.reorder_level) - parseFloat(i.quantity)),
      ]),
      margin: { left: MARGIN, right: MARGIN },
      headStyles: { fillColor: [200, 40, 40], textColor: 255, fontStyle: 'bold', fontSize: 8 },
      bodyStyles: { fontSize: 8, textColor: [180, 30, 30] },
      alternateRowStyles: { fillColor: [255, 248, 248] },
    })
  }

  drawFooter(doc, generated_by, generated_at)
  doc.save(`Inventory_Catalog_${new Date().toISOString().slice(0,10)}.pdf`)
}

// ── PDF 2 — Stock In Report ────────────────────────────────────────────

export function generateStockInPdf(data) {
  const { school, transactions = [], date_from, date_to, generated_by, generated_at } = data

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const periodLabel = (date_from || date_to)
    ? `Period: ${formatDate(date_from)} – ${formatDate(date_to)}`
    : 'All Time'
  const subtitle = `${periodLabel}  |  Generated: ${formatDate(generated_at)}  |  By: ${generated_by || 'Administrator'}`

  let y = drawHeader(doc, school, 'STOCK IN REPORT', subtitle)

  const totalQtyByItem = transactions.reduce((acc, t) => {
    acc[t.item_name] = (acc[t.item_name] || 0) + parseFloat(t.quantity)
    return acc
  }, {})

  y = drawSummaryBox(doc, y, [
    { label: 'Total Transactions',   value: transactions.length },
    { label: 'Unique Items Received', value: Object.keys(totalQtyByItem).length },
  ])

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Item Name', 'Category', 'Qty Received', 'Vendor / Supplier', 'Remarks', 'Recorded By']],
    body: transactions.map(t => [
      formatDate(t.date),
      t.item_name,
      t.category,
      `${formatQty(t.quantity)} ${t.unit}`,
      t.vendor || '—',
      t.remarks || '—',
      t.performed_by_name || '—',
    ]),
    margin: { left: MARGIN, right: MARGIN },
    headStyles: { fillColor: [30, 140, 70], textColor: 255, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 35 },
      2: { cellWidth: 25 },
      3: { cellWidth: 22, halign: 'right' },
      4: { cellWidth: 28 },
      5: { cellWidth: 32 },
      6: { cellWidth: 25 },
    },
    alternateRowStyles: { fillColor: [245, 255, 250] },
  })

  // Subtotals
  const subtotalY = doc.lastAutoTable.finalY + 6
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 30)
  doc.text('Summary by Item', MARGIN, subtotalY)

  autoTable(doc, {
    startY: subtotalY + 3,
    head: [['Item Name', 'Total Qty Received']],
    body: Object.entries(totalQtyByItem).map(([name, qty]) => {
      const unit = transactions.find(t => t.item_name === name)?.unit || ''
      return [name, `${formatQty(qty)} ${unit}`]
    }),
    margin: { left: MARGIN, right: MARGIN },
    headStyles: { fillColor: [60, 80, 180], textColor: 255, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 100 },
      1: { cellWidth: 40, halign: 'right' },
    },
    tableWidth: 145,
  })

  // Authorisation block
  let authY = (doc.lastAutoTable?.finalY || 250) + 12
  if (authY > 268) {
    doc.addPage()
    authY = 20
  }
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text('Authorised By: _______________________________', MARGIN, authY)
  doc.text('Date: _____________________', MARGIN + 110, authY)
  doc.text('Designation: _______________________________', MARGIN, authY + 7)

  drawFooter(doc, generated_by, generated_at)
  doc.save(`Stock_In_Report_${new Date().toISOString().slice(0,10)}.pdf`)
}

// ── PDF 3 — Stock Out Report ───────────────────────────────────────────

export function generateStockOutPdf(data) {
  const { school, transactions = [], low_stock_items = [], date_from, date_to, generated_by, generated_at } = data

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const periodLabel = (date_from || date_to)
    ? `Period: ${formatDate(date_from)} – ${formatDate(date_to)}`
    : 'All Time'
  const subtitle = `${periodLabel}  |  Generated: ${formatDate(generated_at)}  |  By: ${generated_by || 'Administrator'}`

  let y = drawHeader(doc, school, 'STOCK OUT / ISSUE REPORT', subtitle)

  const totalQtyByItem = transactions.reduce((acc, t) => {
    acc[t.item_name] = (acc[t.item_name] || 0) + parseFloat(t.quantity)
    return acc
  }, {})

  y = drawSummaryBox(doc, y, [
    { label: 'Total Issues',      value: transactions.length },
    { label: 'Unique Items',      value: Object.keys(totalQtyByItem).length },
    { label: 'Low Stock Alerts',  value: low_stock_items.length },
  ])

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Item Name', 'Category', 'Qty Issued', 'Issued To / Remarks', 'Issued By']],
    body: transactions.map(t => [
      formatDate(t.date),
      t.item_name,
      t.category,
      `${formatQty(t.quantity)} ${t.unit}`,
      t.remarks || '—',
      t.performed_by_name || '—',
    ]),
    margin: { left: MARGIN, right: MARGIN },
    headStyles: { fillColor: [180, 40, 40], textColor: 255, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 38 },
      2: { cellWidth: 28 },
      3: { cellWidth: 22, halign: 'right' },
      4: { cellWidth: 48 },
      5: { cellWidth: 28 },
    },
    alternateRowStyles: { fillColor: [255, 248, 248] },
  })

  // Subtotals
  const subtotalY = doc.lastAutoTable.finalY + 6
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 30)
  doc.text('Summary by Item', MARGIN, subtotalY)

  autoTable(doc, {
    startY: subtotalY + 3,
    head: [['Item Name', 'Total Qty Issued']],
    body: Object.entries(totalQtyByItem).map(([name, qty]) => {
      const unit = transactions.find(t => t.item_name === name)?.unit || ''
      return [name, `${formatQty(qty)} ${unit}`]
    }),
    margin: { left: MARGIN, right: MARGIN },
    headStyles: { fillColor: [60, 80, 180], textColor: 255, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 100 },
      1: { cellWidth: 40, halign: 'right' },
    },
    tableWidth: 145,
  })

  // Low stock warnings
  if (low_stock_items.length > 0) {
    const warnY = doc.lastAutoTable.finalY + 8
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(200, 40, 40)
    doc.text('⚠  Items Currently Below Reorder Level', MARGIN, warnY)

    autoTable(doc, {
      startY: warnY + 3,
      head: [['Item Name', 'Unit', 'Current Stock', 'Minimum Level', 'Shortfall']],
      body: low_stock_items.map(i => [
        i.name, i.unit,
        formatQty(i.quantity),
        formatQty(i.reorder_level),
        formatQty(parseFloat(i.reorder_level) - parseFloat(i.quantity)),
      ]),
      margin: { left: MARGIN, right: MARGIN },
      headStyles: { fillColor: [200, 40, 40], textColor: 255, fontStyle: 'bold', fontSize: 8 },
      bodyStyles: { fontSize: 8, textColor: [180, 30, 30] },
      alternateRowStyles: { fillColor: [255, 248, 248] },
    })
  }

  // Auth block
  let authY = (doc.lastAutoTable?.finalY || 250) + 12
  if (authY > 268) {
    doc.addPage()
    authY = 20
  }
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text('Authorised By: _______________________________', MARGIN, authY)
  doc.text('Date: _____________________', MARGIN + 110, authY)
  doc.text('Designation: _______________________________', MARGIN, authY + 7)

  drawFooter(doc, generated_by, generated_at)
  doc.save(`Stock_Out_Report_${new Date().toISOString().slice(0,10)}.pdf`)
}

// ── PDF 4 — Low Stock Alert Report ─────────────────────────────────────

export function generateLowStockPdf(data) {
  const { school, items = [], generated_by, generated_at } = data

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })

  const subtitle = `Generated: ${formatDate(generated_at)}  |  By: ${generated_by || 'Administrator'}`
  let y = drawHeader(doc, school, 'LOW STOCK ALERT REPORT', subtitle)

  const categoriesCount = [...new Set(items.map(i => i.category))].length

  y = drawSummaryBox(doc, y, [
    { label: 'Items Below Limit',    value: items.length },
    { label: 'Categories Affected',  value: categoriesCount },
    { label: 'Immediate Action Req', value: items.length > 0 ? 'YES' : 'NO' },
  ])

  autoTable(doc, {
    startY: y,
    head: [['#', 'Item Name', 'Category', 'Unit', 'Current Stock', 'Min Level', 'Shortfall']],
    body: items.map((item, idx) => [
      idx + 1,
      item.name,
      item.category,
      item.unit,
      formatQty(item.quantity),
      formatQty(item.reorder_level),
      formatQty(parseFloat(item.reorder_level) - parseFloat(item.quantity)),
    ]),
    margin: { left: MARGIN, right: MARGIN },
    headStyles: { fillColor: [200, 40, 40], textColor: 255, fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fontSize: 8, textColor: [180, 30, 30] },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 55 },
      2: { cellWidth: 30 },
      3: { cellWidth: 20, halign: 'center' },
      4: { cellWidth: 22, halign: 'right' },
      5: { cellWidth: 22, halign: 'right' },
      6: { cellWidth: 22, halign: 'right' },
    },
    alternateRowStyles: { fillColor: [255, 248, 248] },
  })

  // Footer note
  const footerNoteY = doc.lastAutoTable.finalY + 10
  doc.setFontSize(8)
  doc.setFont('helvetica', 'italic')
  doc.setTextColor(120, 120, 120)
  doc.text('Note: Shortfall indicates the minimum quantity required to reach the reorder level.', MARGIN, footerNoteY)

  drawFooter(doc, generated_by, generated_at)
  doc.save(`Low_Stock_Alert_${new Date().toISOString().slice(0,10)}.pdf`)
}
